version: '3'

services:
  web:
    build: .
    command: sh -c "python scripts/create_log_files.py && python manage.py migrate && gunicorn -c gunicorn_config.py main.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"